apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-z0aa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-riox-tenant/rhtap-demo-app/hacbs-test-project-z0aa@sha256:377d4160fc4052df07bccce670ffb327d7eb88b932736c667e7cca5b86ef8cc0
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
